algoritmo "Exe09"
//Faça um algoritmo que o usuário deverá digitar seu nome e três números e o programa irá multiplicar o produto desses números.
var
nome:caracter
produto,n1,n2,n3:real

inicio
escreva("Digiter o Nome do usuario: ")
leia(nome)
escreva("Digiter o Primeiro numero: ")
leia(n1)
escreva("Digiter o Segundo numero: ")
leia(n2)
escreva("Digiter o Terceiro numeiro: ")
leia(n3)

produto <-n1*n2*n3

escreva("O produto dos numeros: ",n1 ,"",n2,"",n3)


fimalgoritmo