algoritmo "Exe04"
//Crie um Algoritmo que declaramos três variáveis e na terceira variável vai receber o nome + sobrenome e imprimir o nome completo.
var
nome,sobrenome,nomecompleto:caracter

inicio
  escreva("Digiter seu Nome: ")
  leia(nome)
  escreva("Digiter seu Sobrenome: ")
  leia(sobrenome)

   nomecompleto <-nome +""+ sobrenome
   escreva("Seu Nome Completo é: " ,nome,sobrenome,nomecompleto)


fimalgoritmo