algoritmo "Exe08"
//Faça um programa que receba os nomes de 5 alunos e informe que "Os cincos alunos de logica de programação são:" " mostre todos na mesma linha.
var
 Aluno,Ana,Pedro,Luiz,Beatriz,Iago:caracter


inicio
Aluno <-"Ana"
Aluno <-"Pedro"
Aluno <-"Luiz"
Aluno <-"Beatriz"
Aluno <-"Iago"
leia(Ana)
leia(Pedro)
leia(Luiz)
leia(Beatriz)
leia(Iago)

escreva("Os cincos alunos de logica de programação são:",ana,pedro,luiz,beatriz,iago)


fimalgoritmo