algoritmo "Nome do Programa"
 //Faça um algoritmo que leia a altura e largura de uma parede.  Mostre quantos metros quadrados a parede tem.
var
altura:real
largura:real
m0:real


inicio
escreva("Digiter a altura:")
leia(altura)
escreva("Digiter a largura:")
leia(largura)

m0 <-altura * largura

escreva("Mostre quantos metros quadrados a parede tem",m0,"Quantos Metros quadrados:")


fimalgoritmo