algoritmo "Nome do Programa"
//Faça um algoritmo que o usuário deverá digitar três números e o programa irá mostrar o processo de multiplicação passo a passo antes de exibir o resultado final.
var
n1,n2,n3,mult:inteiro


inicio
escreva("Digiter O Primeiro Numero:")
leia(n1)
escreva("Digiter O Segundo Numero:")
leia(n2)
escreva("Digiter O Terceiro Numero:")
leia(n3)

mult <-n1*n2*n3

escreva("O resultado final da mult é:",mult)

fimalgoritmo