algoritmo "Nome do Programa"
// Faça um algoritmo que leia um número real e mostre na tela o seu dobro e a sua terça parte.
var
numero:real
dobro:real
tercaparte:real


inicio
escreva("Digite um numero real:")
leia(numero)

dobro <-numero * 2
tercaparte <- numero /3

escreva("O numero digitado foi: ",numero)
escreva("O dobro do numero é: ",dobro)
escreva("A terça parte do numero é: ",tercaparte)



fimalgoritmo