algoritmo "Nome do Programa"
//Faça um algoritmo que leia o salário de um funcionário, calcule e mostre o seu novo salário, com 15% de aumento.
var
salario_atual,novo_salario:real



inicio
escreva("Digite o salario atual do Funcionario:")
leia(salario_atual)

novo_salario := salario_atual + salario_atual

escreva("O novo salario com 15% de aumento é: ",salario_atual,"",novo_salario,"")


fimalgoritmo