algoritmo "Nome do Programa"
//Faça um algoritmo que o programa leia as duas notas de um aluno em uma matéria e mostre na tela a sua média na disciplina.
var
nota1,nota2:real
media:real


inicio
escreva("Digiter a Primeira Nota:")
leia(nota1)
escreva("Digiter a Segundo Nota:")
leia(nota2)

media <-(nota1 + nota2) /2

escreva("A Media Entre:",nota1 ," é " ,nota2, " é igual a:")

fimalgoritmo