algoritmo "Nome do Programa"
 //Faça um programa que leia dois números inteiros e exiba o resultado da divisão inteira do maior pelo menor. 
var
maior_numero,menor_numero:inteiro
divisao:inteiro


inicio
escreva("Digiter o maior numero:")
leia(maior_numero)
escreva("Digiter o menor numero:")
leia(menor_numero)

divisao <-maior_numero div menor_numero

escreva("Resultado da divisao é:",divisao)


fimalgoritmo