algoritmo "Nome do Programa"
 //Crie um programa usando o "Repita" que imprima a tabuada de um número digitado pelo usuário.
var
numero:inteiro
contador:inteiro
resultado:inteiro


inicio
escreva("digite um numero ver sua tabuada:")
leia(numero)
contador <-1
repita 
resultado <- contador * numero
escreval(contador,"x",numero,"=",resultado)
contador <- contador 1
ate numero >10



fimalgoritmo