algoritmo "Nome do Programa"
 //Faça um programa que leia a nota de um aluno e verifique se ele foi aprovado (nota maior ou igual a 7) ou reprovado.
var
aluno:caracter
nota:real

inicio
escreva("Digiter o nome do aluno:")
leia(aluno)
escreva("Digiter a nota do aluno maior que sete ou igual a sete:")
leia(nota)

se nota >=7 entao
escreva("o aluno esta aprovado!")
senao
escreva("o aluno esta reprovado!")
    
fimse

fimalgoritmo