algoritmo "Nome do Programa"
//Faça um programa que leia o ano de nascimento de uma pessoa, calcule a idade dela e depois mostre se ela pode ou não votar.
var
nome:caracter
idade:inteiro
votar: caracter
inicio
escreva("Digiter seu nome:")
leia(Nome)
escreva("Digiter Ano que voce narceu:")
leia(idade)

idade <-2024-idade
  se idade>=18 entao
escreva("entao vc é maior de idade pode vota")
  senao
escreva("ser for menor de idade não pode votar")

fimse


fimalgoritmo