algoritmo "Nome do Programa"
//Faça um programa que leia um número inteiro e determine se ele é divisível por 5 utilizando o operador de resto. Mostre "Divisível por 5" ou "Não divisível por 5"
var
numero:inteiro
divisivel:inteiro


inicio
escreva("Digite o nuemro:")
leia(numero)

divisivel <-numero %5

se divisivel= 0 entao
escreva("O numero é divivel por 5")
senao
escreva("O numero não é divivel por 5")

fimse

fimalgoritmo