algoritmo "Nome do Programa"
//Faça um programa que leia a idade de uma pessoa e verifique se ela é maior de idade (18 anos ou mais)
var
idaade:inteiro
nome:caracter


inicio
escreva("Digiter a sua idade:")
leia(idade)
escreval("Digiter seu nome:")
leia(nome)

  se idade >= 18 entao
escreval("voce é maior de idade.")
  senao
escreval("voce é menor de idade.")

fimse


fimalgoritmo