algoritmo "Nome do Programa"
//Escreva um algoritmo que receba dois números inteiros e determine se eles são iguais ou diferentes.
var
num1,num2:inteiro


inicio
escreva("Digite o primeiro numero:")
leia(num1)
escreva("Digite o segundo numero:")
leia(num2)

se num1 = num2 entao
escreva("os numeros sao iguais.")
senao
escreva("os numeros sao diferentes.")

fimse



fimalgoritmo