algoritmo "Nome do Programa"
//Faça um programa que solicite ao usuário para digitar números e informe "Número recebido" a cada vez que o usuário digitar um novo número. O programa deve parar quando o usuário digitar "0".
var
numero:real
contador:real

inicio
numero<-1
enquanto(numero<> 0)faca
escreva("O programa deve parar quando o usuario(digitar 0)")
leia(numero)

contadpr<-contador +1
fimenquanto
escreva("O programa encerrar com suceso")


fimalgoritmo